import os
import json
import time
import csv
import datetime
import krpc

from kspdg.agent_api.base_agent import KSPDGBaseAgent
from kspdg.agent_api.runner import AgentEnvRunner
from kspdg.pe1.e1_envs import PE1_E1_I3_Env

class LLM2ExecutorAgent(KSPDGBaseAgent):
    """
    Agent that reads a fixed plan generated by LLM1 (stored in a JSON file) and applies it in the environment
    without reasoning or generating any new plans.
    """
    def __init__(self):
        super().__init__()

        try:
            self.conn = krpc.connect()
            self.vessel = self.conn.space_center.active_vessel
            self.body = self.vessel.orbit.body
        except Exception as e:
            print("Exception while connecting to kRPC:", e)
            self.conn = None
            self.vessel = None
            self.body = None

        self.duration = 0.5
        self.plan = self._load_plan()
        self.log = self._setup_logger()

    def _load_plan(self):
        with open("plan_p1_llm1.json", "r") as f:
            return json.load(f)

    def _setup_logger(self):
        today_date = datetime.datetime.now().strftime("%m-%d-%Y")
        logs_folder = os.path.join("training_data", f"logs_{today_date}")
        os.makedirs(logs_folder, exist_ok=True)
        log_path = os.path.join(logs_folder, f"llm2_log_pe1_e1_i3_{datetime.datetime.now().strftime('%Y%m%d-%H%M%S')}.csv")
        log_file = open(log_path, mode='w', newline='')
        csv.writer(log_file).writerow(["ft", "rt", "dt", "duration"])
        return log_file

    def get_action(self, observation):
        ft = self.plan.get("ft", 0)
        rt = self.plan.get("rt", 0)
        dt = self.plan.get("dt", 0)

        burn_vec = [ft, rt, dt, self.duration]
        csv.writer(self.log).writerow([ft, rt, dt, self.duration])
        self.log.flush()

        time.sleep(1)
        return {
            "burn_vec": burn_vec,
            "ref_frame": 0
        }

if __name__ == "__main__":
    agent = LLM2ExecutorAgent()
    runner = AgentEnvRunner(
        agent=agent,
        env_cls=PE1_E1_I3_Env,
        env_kwargs=None,
        debug=True
    )
    runner.run()
